---
# yamllint disable rule:line-length
name: Verify and Bump
on:
  schedule:
    - cron: "00 7 * * SUN"
  workflow_dispatch:
  push:
    branches:
      - master
env:
  terraform: 0.14.8
  tf_target_dir: example/examplea
  branch: master
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.branch }}
          token: ${{ github.token }}
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.terraform }}
          tf_actions_subcommand: init
          tf_actions_working_dir: ${{ env.tf_target_dir }}
      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.terraform }}
          tf_actions_subcommand: validate
          tf_actions_working_dir: ${{ env.tf_target_dir }}
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.branch }}
          token: ${{ github.token }}
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          pip3 install lastversion
          now=$(lastversion terraform-docs/terraform-docs)
          mkdir $GITHUB_WORKSPACE/bin
          curl -Lo $GITHUB_WORKSPACE/bin/terraform-docs https://github.com/terraform-docs/terraform-docs/releases/download/v${now}/terraform-docs-v${now}-$(uname)-amd64
          chmod +x $GITHUB_WORKSPACE/bin/terraform-docs
          echo "$GITHUB_WORKSPACE/bin" >> $GITHUB_PATH
      - uses: pre-commit/action@v2.0.0
  version:
    name: versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Bump version and push tag
        if: ${{ !env.ACT }}
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: "true"
    needs: [terraform, security]
